### ISSUE TITLE
OpenWRT on Raspberry Pi 3B: CPU info not working

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#28] opened 2021-11-23 00:56 UTC
This may be a tricky one to fix, as the `/proc/cpuinfo` output is very different from Intel/AMD. Current output of fetch for this line:

```bash
cpu ~ ash: GenuineIntel: unknown operand
```

Output of /proc/cpuinfo for this board:

```
root@Ron:~/bin# cat /proc/cpuinfo 
processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 00000000e85bd3ff
Model           : Raspberry Pi 3 Model B Rev 1.2
```

With no vendor_id to sort from, there's almost no commonality to work with here. For comparison, I'll also include cpuinfo for two other embedded systems I've been working with a lot.

RB750Gr3 (first core only, nothing varies on the other three):

```
system type             : MediaTek MT7621 ver:1 eco:3
machine                 : MikroTik RouterBOARD 750Gr3
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 584.90
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit cdmm nan_legacy nan_2008 perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

MT300Nv2 (single core and very low energy use):

```
system type             : MediaTek MT7628AN ver:1 eco:2
machine                 : GL-MT300N-V2
processor               : 0
cpu model               : MIPS 24KEc V5.5
BogoMIPS                : 380.92
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit nan_legacy nan_2008 perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

Not a lot of commonality. For the non-x86 boards, the most common thing I'm seeing that might be a useful alternative is the "system type" field, but the Pi doesn't even have that.

This issue's definitely a bit of an open-ended question for what to do for non-desktop systems - or how into the weeds you even want to get trying to support them. A fetch script this light has potential to be _really_ useful on these little embedded systems, but there are just so many edge cases!

**Comment by wick3dr0se** [comment] 2021-11-23 01:23
Duplicate of issue #23 

Thank you for providing information from all of your devices! Can you test my last commit? It should hide now hopefully.. This could be stubborn

**Comment by nathhad** [comment] 2021-11-23 01:41
Pulling most current version and testing now, results to follow!

**Comment by nathhad** [comment] 2021-11-23 01:53
Not working at present, output is:

```bash
cpu ~ ash: GenuineIntel: unknown operand
```

I think the issue is in the line

```bash
elif $vendor ; [[ $vendor =~ "GenuineIntel" ]] ; then
```

Something doesn't look quite right there to me - but I haven't quite parsed what yet. But ash is parsing that line in such a way that it's thinking "GenuineIntel" is a command, and throwing quotes around it hasn't helped. Will continue to poke it with a stick and see if I can see what's going on with it.

**Comment by nathhad** [comment] 2021-11-23 01:58
Potential progress, switching that line to:

```bash
elif [[ "$vendor" =~ "GenuineIntel" ]] ; then
```
Resolves the error text within the output, and gets us back to output that looks like this:

```
cpu ~ 1.2@1.00GHz
```

Which looks perfectly serviceable! That may be the fix since we don't have an easily identifiable chip name for this one.

That said, I did also import it to a couple of my slightly older models with older ash compiles, and they do have trouble with the `=~` operand:

```bash
cpu ~ ash: =~: unknown operand
```
That should hopefully be a little easier to resolve.

Need to get ready to crash for the night, so I may get slow to respond! I'll probably have to pick back up tomorrow morning.

**Comment by wick3dr0se** [comment] 2021-11-23 01:59
I pushed a commit that I think will fix it. I did not notice that 'GenuineIntel' was not parsed as a string

**Comment by nathhad** [comment] 2021-11-24 16:39
Okay, testing on this one as of commit 8ad5a71

Output:

```bash
cpu ~ -ash: ./components/cpu_gpu.sh: =~: not found
```

This one is at least easy to explain as `=~` is a bash-only comparison operator, and is what's causing the issue under ash. I was able to fix this quickly on my local copy by editing line 8 to the following:

```bash
elif $vendor && [[ "$vendor" = "GenuineIntel" ]] ; then
```

That provides the following simplified result (but still works fine on my other Debian11/x86 test machine):

```bash
cpu ~ 1.20@1.0GHz
```

That to me I would consider 100% okay on a board like this that provides so little cpu info, it's basically ideal.

**Comment by wick3dr0se** [comment] 2021-11-24 18:32
Thank you for your testing and solution! I made the changes you requested. I can't verify because I have AMD cpu but it should be good. Closing now as solved!

**Closed as completed** 2021-11-24 18:36 UTC

**Comment by nathhad** [comment] 2021-11-24 20:59
Testing on commit 579d217 and don't see the change working - I do see line 8 was changed, but the line as changed still causes errors.

Current code: `elif $vendor && [[ $($vendor = GenuineIntel) ]] ; then`

Error output: `components/cpu_gpu.sh: line 8: =: not found`

Recommended syntax: `elif $vendor && [[ "$vendor" = "GenuineIntel" ]] ; then`

Output:
ash/busybox/openwrt: `cpu ~ 1.20@1.0GHz` (expected and good)
bash/debian11/x86: `cpu ~ Intel Core i7        M 640   2.80GHz2.7@2.15GHz` (also still good)

The output on x86 on my machine does include a lot of extra whitespace that for some reason doesn't get reproduced when I copy it in here, but that's a whole separate little quirk that can be prettied up later.
