### ISSUE TITLE
Correctness of terminal detection depends on how the script is called

### ISSUE THREAD

**Issue by Popkornium18** [wick3dr0se/fetch.sh#15] opened 2021-11-22 16:11 UTC
An example:

```
./fetch.sh
[...]
term ~ alacritty shell ~ bash

bash fetch.sh
[...]
term ~ bash shell ~ bash
```

**Comment by wick3dr0se** [comment] 2021-11-22 22:49
I believe this is due to terminal being identified by PID, maybe running bash updates the process tree and causes it to find the shell instead

**Comment by Popkornium18** [comment] 2021-11-23 10:27
Calling a script with `bash script.sh` doesn't spawn a new process called `script.sh` but a new process called `bash`.

```
$ ./asd.sh
systemd---alacritty---bash---asd.sh---pstree
systemd---alacritty
alacritty
$ bash asd.sh
systemd---alacritty---bash---bash---pstree
systemd---alacritty---bash
bash
```

**Comment by wick3dr0se** [comment] 2021-11-23 22:14
@SimoneSalzano's commit 451e47b68faaa0515dfc25e0cef3cb254973005b should fix this issue

**Comment by Popkornium18** [comment] 2021-11-23 23:59
The fix introduced a regression. The program can't detect a terminal emulator that has been launched from another terminal anymore.

```
$ ./fetch.sh # in alacritty
[...]
term ~ alacritty shell ~ bash
$ xterm
$ ./fetch.sh # now in xterm
term ~ alacritty shell ~ bash
```

This worked fine before.

**Comment by th4tkh13m** [comment] 2021-11-24 01:20
This explains why I get `login` terminal since I do use `startx` in the tty.

**Comment by SimoneSalzano** [comment] 2021-11-24 10:19
@Popkornium18, can you show me the output of  `pstree -sA $$` while you are in xterm? I'm trying to reproduce the bug with other terminals called within other terminals but it seems to work fine.

**Comment by Popkornium18** [comment] 2021-11-24 10:36
```
$ pstree -sA $$
systemd---alacritty---bash---xterm---bash---pstree
```

**Comment by Popkornium18** [comment] 2021-11-24 11:12
See #42

**Comment by wick3dr0se** [comment] 2021-11-25 17:28
Can you run latest alpha build and test the current output? I believe this issue is solved

**Comment by Popkornium18** [comment] 2021-11-25 17:37
It is not, unfortunately. Launching xterm from alacritty now prints this.

```
term ~ alacritty------xterm shell ~ bash
```

**Comment by wick3dr0se** [comment] 2021-11-25 18:03
Ez fix give me one second. Try alpha now. Should be good to go

**Comment by wick3dr0se** [comment] 2021-11-25 18:07
Try alpha now. Should be good to go

**Comment by Popkornium18** [comment] 2021-11-25 18:23
Now it's back to reporting alacritty in xterm.

**Comment by wick3dr0se** [comment] 2021-11-25 18:38
I'm confused because a quick search tells me that alacritty is a terminal emulator just like xterm. Do you want xterm to print? Also, why would you launch a terminal from another terminal? Genuinely curious because that creates a whole seperate issue..

**Comment by Popkornium18** [comment] 2021-11-25 18:48
Yes, neofetch detects this correctly, so why shouldn't this tool?
![image](https://user-images.githubusercontent.com/46488511/143489842-c539dfb7-bc6a-4172-8291-b4aa35e962d8.png)

Excuse the nonexistent theming on xterm, looks horrible, I know.

**Comment by wick3dr0se** [comment] 2021-11-25 18:52
I'm not saying this tool shouldn't; I'm not even sure why you would ask that question. I didn't imply that I'm not willing to fix your issue and you still didn't anwer what I asked you. It's kind of pointless assume things like that when someones trying to help you

**Comment by Popkornium18** [comment] 2021-11-25 19:01
That was just my reasoning why I think this would be nice to support, not as an insult. Sorry if it came off as rude, wasn't my intention.

Xterm would be the correct result in this case. There is no specific reason to launch a terminal emulator from another one other than because it works. It might be faster than launching it the regular way if you are already in the terminal and needed to access another terminal-emulator.

**Comment by wick3dr0se** [comment] 2021-11-25 19:09
I apologize for taking it wrong but I may keep the functionaly as is because in 99% use cases people won't be launching a terminal from within a terminal. I don't think supporting such an odd case like this would be worth the implementation. Right now I wrote a variable called shell_strip im using to strip shell names from pstree output. If I have to strip a terminal name because it was spawning in process tree from being launched like that then I have to hard path strip xterm or alacritty out, which will cause 1 or the other not to print if someone is using that terminal. With the current state of the code it isn't viable to strip terminal names from the output

Technically the terminal isn't even detected it's just the only variable I don't strip from pstree output. I launch my terminal with Win+Enter. If I was to use a second shell it would likely be mapped to Win+t or something. I think launching a terminal within a terminal is redundant because it makes the terminal run that process itself which makes the previous one unusable anyway. You should be able to find a terminal that supports all your features. I find that xterm, xfce4-terminal, kitty and uxrvt all function as intended on my system with unicode characters and all. Hopefully people won't be launching this way

**Comment by Popkornium18** [comment] 2021-11-25 19:17
Would probably be fine, but you could always do it the way [Neofetch](https://github.com/dylanaraps/neofetch/blob/d4070d515d25402da06c2aea8ea04fe8f0dc3148/neofetch#L3289) does. There is no edge case handling necessery the way it's implemented there.

**Comment by wick3dr0se** [comment] 2021-11-25 19:22
Looking at code like that is the whole entire reason I started this. Like for example I just looked at it and I can understand it for the majority of it but $parent variable isn't even visible. Like I'm not gonna read 1k lines to find an easter egg variable. I hate that code can't just be organized and readable.. They do this on purpose then call it open source. That's some giberish is what it is

**Comment by Popkornium18** [comment] 2021-11-25 19:51
It works like this: `$parent` is undefined in the first iteration of the loop and gets updated in each iteration. `get_ppid()` returns `$PPID` if no parameter (a PID) was defined (like in the first iteration). If there is a PID parameter, its Parent PID will be returned.

Essentially this `get_term()` function boils down to: Keep walking up the parent processes, grabbing the executable name for each process, until you see the first process name that is not a shell. It looks a bit intimidating, but it is not intentionally obfuscated IMO.

**Comment by wick3dr0se** [comment] 2021-11-25 20:26
Maybe we can create a new script in the gamma branch to test this. That makes sense to me now I just have to figure out how to implement it. Right now i'm at family Thanksgiving, I'll be back home this evening and then I can attempt to work on this

**Comment by th4tkh13m** [comment] 2021-11-26 01:06
The commit you told me just hide the output, @wick3dr0se. Now it does not show `st-256color` but a blank space only. Here is my output (same for master and alpha branch)
![image](https://user-images.githubusercontent.com/29520244/143512276-497466ce-8841-4487-84e1-ec2835e24896.png)

**Comment by wick3dr0se** [comment] 2021-11-26 03:27
Can you run latest alpha build? I tried to fix all your issues at once

**Comment by th4tkh13m** [comment] 2021-11-26 03:51
Here is my new output at alpha
![image](https://user-images.githubusercontent.com/29520244/143524142-bd8cdf0a-dc2a-43b7-b45f-daffe24ea630.png)

**Comment by wick3dr0se** [comment] 2021-11-26 04:10
Should be fixed now. Are you using TTY so no de/wm, theme or terminal?

**Comment by th4tkh13m** [comment] 2021-11-26 05:26
I'm not using a TTY but I'm launching Xorg by the command `startx` in the TTY.
- DE/WM: There is no `xprop` package in the `xorg-minimal` of Void Linux, so the command fail at the if statement. (Low priority)
- GTK theme: `gsettings` is available, but its interface `org.gnome.desktop.interface` is not (don't get why).  Therefore, the output of the command is blanked.
- Term: I do not have the the `pstree` command, but the `$TERM` works well for me (printing `st-256color` in st and `linux` in the TTY). But in the code, since my `$SHELL` is not empty (`bash`), the first if statement is executed, thus leads to a blank information.

**Comment by wick3dr0se** [comment] 2021-11-29 01:56
The main issue was solved in this issue, I believe several of those, if not all *should* be fixed. If any errors exist just open up a new issue!

**Closed as completed** 2021-11-29 01:57 UTC
