### ISSUE TITLE
Regressions with de/wm and theme

### ISSUE THREAD

**Issue by IndrekHaav** [wick3dr0se/fetch.sh#18] opened 2021-11-22 17:45 UTC
Some recent commit introduced an error under WSL2:

```
de/wm ~ de/wm ~ xprop:  unable to open display ''
```

Presumably the same can happen on other headless systems.

The label is also shown twice, because of [line 47](https://github.com/wick3dr0se/fetch.sh/blob/master/fetch.sh#L47).

On a RPi4 running Ubuntu 20.04, `xprop` isn't found:

```
de/wm ~ de/wm ~ ./fetch.sh: line 48: xprop: command not found
```

Also, the "theme" label is indented, and under WSL2 also prints the path to `gsettings`:

```
 theme ~ /usr/bin/gsettings
'Adwaita'
```

Maybe instead of `command -v gsettings`, run `which gsettings` and test its return code?

**Comment by IndrekHaav** [comment] 2021-11-22 17:53
Some of these might be duplicates of #16 and #17, sorry, didn't see those before posting this.

**Comment by wick3dr0se** [comment] 2021-11-22 17:54
Can you run it again? I'm working on that right now and just made 3 commits. Post full output so I can see whats going on easier

**Comment by IndrekHaav** [comment] 2021-11-22 17:55
Now under WSL2 getting this:

```
de/wm ~ /usr/bin/xprop
xprop:  unable to open display ''
```

Same suggestion as with gsettings - test with `which` instead of `command`?

**Comment by wick3dr0se** [comment] 2021-11-22 18:00
It should work now. I accidentally left out the square brackets surrounding xprop and gsettings, if not I will attempt with which next

**Comment by wick3dr0se** [comment] 2021-11-24 19:21
This should be fixed with -z $DISPLAY on commit 433c555. Please pull latest commit and test so we can get this issue closed!

**Comment by IndrekHaav** [comment] 2021-11-24 19:26
On a RPi4 running Ubuntu 20.04, I get:

```
theme ~ ./components/de-wm_theme.sh: line 20: gsettings: command not found
```

In Debian 10 under WSL2, I get:

```
theme ~ No schemas installed
```

Not sure if this is a bug or intended.

Also, the "theme" row is still indented.

**Comment by wick3dr0se** [comment] 2021-11-24 19:42
That should have fixed your issue with gsettings output. The issue is likely that you have no theme at all but the path shouldn't output at all because it's irrelevant info. No schemas installed likely prints from xprop and I would consider it a good output to keep, if that fails next it will echo not found. Theme row is hard indented on purpose, de/wm should output not found or your theme name and theme should be in same row indented to the side

**Comment by IndrekHaav** [comment] 2021-11-24 19:46
I'll make a PR for the newline/indendation issue, seems like a really simple fix.

**Comment by wick3dr0se** [comment] 2021-11-24 19:55
I'll close this as solved then! Thanks alot!

**Closed as completed by wick3dr0se** 2021-11-24 19:55 UTC

**Comment by GavinRay97** [comment] 2021-12-06 00:20
Just as a random note + thank-you, your comment @IndrekHaav was the only Google result when searching for an error that broke my WSL2 distro after trying to `do-release-upgrade`.

If it wasn't for this issue pointing towards `gsettings`, I don't think I would have been able to fix it. So thank you 😃 

![image](https://user-images.githubusercontent.com/26604994/144770110-3092de30-e561-42d6-8453-96c72653814b.png)
