### ISSUE TITLE
Current Build: Theme category not showing:

### ISSUE THREAD

**Issue by saintphaenixos** [wick3dr0se/fetch.sh#37] opened 2021-11-24 00:06 UTC
I'm currently getting this with the current build:

![image](https://user-images.githubusercontent.com/25014799/143147953-03c641ec-e2ce-48e8-8a09-b1937c241542.png)

I think I may have a fix by switching the if and elif in the THEME statement. I'll give it a try.

**Comment by wick3dr0se** [comment] 2021-11-24 00:43
I've tried this change before but on my system it will print theme name from my icon pack with gsettings

**Comment by saintphaenixos** [comment] 2021-11-24 00:44
Dang, I'll poke around with it some more on my end. :+1:

**Comment by saintphaenixos** [comment] 2021-11-24 00:45
Actually after reading it, this should be combined with #32.

This looks to be the same issue.

**Comment by wick3dr0se** [comment] 2021-11-24 01:02
Test commit 4573761f9f16ebe65b29779e5bae5647582833d2 please

**Comment by th4tkh13m** [comment] 2021-11-24 01:18
Here is my output
```
th4tkh13m@myarch
kernel ~ 5.10.81-1-lts
uptime ~ 0 weeks, 0 hours, 0 minutes
os ~ Arch Linux arch ~ x86_64
de/wm ~  theme ~ Nordic
cpu ~ Intel Core i5-8365U   1.60GHz1.30@.8GHz
gpu ~ Intel  WhiskeyLake-U GT2 UHD Graphics 620 (rev 02)
pkgs ~ 494
ram ~ 15816 MiB swap ~ 4095 MiB
term ~ login shell ~ bash
```
The gtk theme looks fine, but not de/wm and now the term part is login.

**Comment by wick3dr0se** [comment] 2021-11-24 01:35
The term part is assigned to @SimoneSalzano, I know nothing about how to fix that string he wrote but commit 433c555940c40b7e0b0d0291e6ff1b14b9e5110c should fix problems with de/wm

**Comment by SaintFenix** [comment] 2021-11-24 01:41
Sorry to say I'm getting this now:

![image](https://user-images.githubusercontent.com/29680981/143155631-8e3f8939-fac1-459f-8fa1-e081563d8362.png)

But I'll try the latest commit.

Edit: Same result with current build.

**Comment by th4tkh13m** [comment] 2021-11-24 01:52
It still not showing I'm using DWM (a blank space) and the de/wm part of SaintFenix is a mess as well (showing too many DE)

**Comment by wick3dr0se** [comment] 2021-11-24 02:03
Curious what last commit did. I need to get a VM up and running to be able to test more

**Comment by th4tkh13m** [comment] 2021-11-24 03:34
There are several things to fix:
- Maybe wrap the grep settings.ini command in an if statment so that no error statement is printed when no settings.ini file is found. Note: An error statement is also printed on machines which have no `gsettings` command (unlikely since it is shipped with GTK package)
- Change the xprop statement in wm part. (We can only get _NET_WM_NAME by using xprop -id with an id of a child window. xprop -root itself does not include _NET_WM_NAME attribute but contains the child window's id.)

**Comment by th4tkh13m** [comment] 2021-11-24 09:45
Can you create Dev branch for testing? We should not always merge the PR into the main branch.

**Comment by wick3dr0se** [comment] 2021-11-24 19:17
I made a fix for this commit 2e6f750 please test and let me know so we can close this issue!

**Comment by saintphaenixos** [comment] 2021-11-24 20:46
Here is my current output, I'm looking good on Ubuntu 21.10 AMD64:

![image](https://user-images.githubusercontent.com/25014799/143310631-a920fba0-1e8b-4f94-a543-90ca2f9e9632.png)

The hours is a different issue.

**Comment by wick3dr0se** [comment] 2021-11-24 21:46
> Can you create Dev branch for testing? We should not always merge the PR into the main branch.

Done! Your other issues should be resolved with the PR and my changes to de/wm

**Comment by saintphaenixos** [comment] 2021-11-24 23:32
I'm looking good on my end for de/wm, here is my current output:

![image](https://user-images.githubusercontent.com/25014799/143325453-2c3b966c-5af0-4bdf-932a-cd3fd5e8c4ef.png)

**Comment by th4tkh13m** [comment] 2021-11-25 01:39
Consider closing this issue if the issue is fixed

**Comment by wick3dr0se** [comment] 2021-11-25 01:56
@th4tkh13m I will, I have a solution for the ss posted here tho
@saintphaenixos Get new commit from alpha and see if it doesn't output 3 different cpu speeds now, please!

Closing as issue at hand was solved. Open new issue for duplicate cpu speed if that issue persist

**Closed as completed** 2021-11-25 03:20 UTC
